# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoscienceSectionVerticalExaggeration
                                 A QGIS plugin
 This plugin creates a vertically exaggerated section of your already created geoscience section.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-06-17
        copyright            : (C) 2025 by Nicola Kern
        email                : nicolajkern@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeoscienceSectionVerticalExaggeration class from file GeoscienceSectionVerticalExaggeration.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .gs_vertical_exaggeration import GeoscienceSectionVerticalExaggeration
    return GeoscienceSectionVerticalExaggeration(iface)
